WorkspaceRoot = "%{_WORKING_DIR}"
ProjectGenFolder = "%{WorkspaceRoot}/#projects"
OutputFolder ="%{WorkspaceRoot}/#build"
CodeFolder = "%{WorkspaceRoot}/code"
ExternFolder = "%{WorkspaceRoot}/extern"